ALTER TABLE "SavedProblem" ADD COLUMN "lastReviewedAt" TIMESTAMP(3), ADD COLUMN "reviewCount" INTEGER NOT NULL DEFAULT 0;
UPDATE "SavedProblem" SET "nextReviewAt" = CURRENT_TIMESTAMP WHERE "nextReviewAt" IS NULL;
ALTER TABLE "SavedProblem" ALTER COLUMN "nextReviewAt" SET NOT NULL, ALTER COLUMN "nextReviewAt" SET DEFAULT CURRENT_TIMESTAMP;
